/*
 * Entrega de Sistemas Inteligentes II
 * Práctica con esquemas y vocabularios usando Twitter
 * José María Amusquívar Poppe
 * 31/03/2021
 */
package com.josesi2.practicajenatwitter;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.jena.atlas.logging.LogCtl;
import org.apache.jena.rdf.model.Model;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.riot.RDFDataMgr;
import org.apache.jena.riot.RDFFormat;
import twitter4j.Status;

/**
 *
 * @author José María
 */
public class PracticaJenaTwitter extends javax.swing.JFrame {

    private final JFileChooser fc = new JFileChooser();
    private FileNameExtensionFilter filter;
    private KeysReader reader;
    private ApiTwitter api;
    private Model modelo;
    private String term;
    
    private SimpleDateFormat sdf;
    
    private String URItweet = "http://si2.com/tweet/";
    private String URIuser = "http://si2.com/user/";
    private String URIlanguage = "http://si2.com/language/";
    private String URItheme = "http://si2.com/theme/";
    private String URIuntheme = "http://si2.com/untheme/";
        
    /**
     * Creates new form FormTwitter
     */
    public PracticaJenaTwitter() {
        initFilters();
        initComponents();
        
        LogCtl.setCmdLogging();
        this.modelo = ModelFactory.createDefaultModel();
        this.modelo.createProperty("http://own.com/reply_to");
        initPrefixes(this.modelo);   
        
        sdf = new SimpleDateFormat("dd/MM/YYYY");
        
        this.outputFile.setSelected(this.ttlFile.getModel(), true);
                        
        this.setLocationRelativeTo(null);
        this.setResizable(false);  
    }
    
    private void initFilters(){
        filter = new FileNameExtensionFilter("Text files", "txt", "text");
        fc.addChoosableFileFilter(filter);
        fc.setAcceptAllFileFilterUsed(false);
    }
    
    private void saveFilters() {
        fc.resetChoosableFileFilters();
        
        filter = (this.ttlFile.isSelected())?
                new FileNameExtensionFilter("Turtle files", "ttl") : 
                new FileNameExtensionFilter("XML files", "xml");
        
        fc.addChoosableFileFilter(filter);
        fc.setAcceptAllFileFilterUsed(false);
    }
        
    public final void initPrefixes(Model modelo) {
        modelo.setNsPrefix("dc", "http://purl.org/dc/elements/1.1/");
        modelo.setNsPrefix("own", "http://own.com/");  
        modelo.setNsPrefix("rdf", "http://www.w3.org/1999/02/22-rdf-syntax-ns#");
        modelo.setNsPrefix("rdfs", "http://www.w3.org/2000/01/rdf-schema#");        
        modelo.setNsPrefix("vcard", "http://www.w3.org/2001/vcard-rdf/3.0#"); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        outputFile = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfTweetsSearched = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        bConnect = new javax.swing.JButton();
        lUsername = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tTermFind = new javax.swing.JTextField();
        tThemeFind = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfDescription = new javax.swing.JTextArea();
        sMaxTweets = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bSearch = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        ttlFile = new javax.swing.JRadioButton();
        xmlFile = new javax.swing.JRadioButton();
        bSave = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tweets Scheme");

        tfTweetsSearched.setColumns(20);
        tfTweetsSearched.setRows(5);
        jScrollPane1.setViewportView(tfTweetsSearched);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("CONEXIÓN"));

        bConnect.setText("CONECTAR");
        bConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConnectActionPerformed(evt);
            }
        });

        lUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lUsername.setText("CARGA TUS CLAVES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bConnect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(158, 158, 158))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bConnect)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tfDescription.setColumns(20);
        tfDescription.setRows(5);
        jScrollPane2.setViewportView(tfDescription);

        sMaxTweets.setModel(new javax.swing.SpinnerNumberModel(1, 1, 50, 1));

        jLabel3.setText("Max. Tweets:");

        jLabel4.setText("Descripción del tema:");

        jLabel2.setText("Tema:");

        jLabel1.setText("Término:");

        bSearch.setText("BUSCAR");
        bSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tThemeFind)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addComponent(tTermFind))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sMaxTweets, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(bSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tTermFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tThemeFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSearch)
                    .addComponent(sMaxTweets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("EXPORTAR GRAFO"));

        outputFile.add(ttlFile);
        ttlFile.setText("Formato TTL");

        outputFile.add(xmlFile);
        xmlFile.setText("Formato XML");

        bSave.setText("GUARDAR");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(ttlFile)
                .addGap(18, 18, 18)
                .addComponent(xmlFile)
                .addGap(36, 36, 36)
                .addComponent(bSave, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSave)
                    .addComponent(xmlFile)
                    .addComponent(ttlFile))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel5.setText("© José María Amusquívar Poppe");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConnectActionPerformed
        if (this.bConnect.getText().equals("DESCONECTAR")) {
            reset();            
            return;
        }
        int res = fc.showOpenDialog(this);
        if (res == JFileChooser.APPROVE_OPTION){
            File selected = fc.getSelectedFile();
            this.reader = new KeysReader(selected.getAbsolutePath());
            if (!this.reader.init()) {
                JOptionPane.showMessageDialog(this, "Fichero erróneo, vuelva a intentarlo",
                        "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            this.api = new ApiTwitter(this.reader.getKeys());    
            this.api.connect();
            
            if(this.api.getUsername().equals("")) {
                JOptionPane.showMessageDialog(this, "No se ha establecido la conexión",
                        "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            this.lUsername.setText("Usuario: " + this.api.getUsername());
            this.bConnect.setText("DESCONECTAR");  
            
            JOptionPane.showMessageDialog(this, "Se ha establecido una conexión", "CONECTADO", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bConnectActionPerformed

    private void reset() {
        this.bConnect.setText("CONECTAR");
        this.lUsername.setText("CARGA TUS CLAVES");
        this.modelo.removeAll();
        this.tfDescription.setText("");
        this.tfTweetsSearched.setText("");
        this.tTermFind.setText("");
        this.tThemeFind.setText("");
        this.sMaxTweets.setValue(1);
    }
    
    private void bSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSearchActionPerformed
        if (this.bConnect.getText().equals("CONECTAR")){
            JOptionPane.showMessageDialog(this, "Establezca una conexión antes de buscar", "DESCONECTADO", JOptionPane.ERROR_MESSAGE);
            return;
        }
        this.term = this.tTermFind.getText();        
        if (this.term.length() <= 0 ||
            this.tThemeFind.getText().length() <= 0 ||
            this.tfDescription.getText().length() <= 0){
            JOptionPane.showMessageDialog(this, "Rellene todos los campos antes de buscar", "INCOMPLETO", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        this.api.pullTweetsByTerm(term, (int) this.sMaxTweets.getValue());
        
        createGraph();
        printTweets();
    }//GEN-LAST:event_bSearchActionPerformed

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        if (modelo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes realizar una búsqueda antes de guardar el modelo", "INCOMPLETO", JOptionPane.ERROR_MESSAGE);
            return;
        }   
        
        saveFilters();
        fc.setDialogTitle("Especifica un lugar donde guardar el modelo");        
         
        int res = fc.showSaveDialog(this);
        if (res != JFileChooser.APPROVE_OPTION) return;
        
        String filename = fc.getSelectedFile().toString();        
        if (!filename.endsWith(".ttl") && this.ttlFile.isSelected()) {
            filename += ".ttl";
        }   
        
        if (!filename.endsWith(".xml") && this.xmlFile.isSelected()) {
            filename += ".xml";
        }
         
        try (OutputStream out = new FileOutputStream(new File(filename))) {
             
            if (this.ttlFile.isSelected()) {
                RDFDataMgr.write(out, modelo, RDFFormat.TURTLE_BLOCKS);
            } else {
                RDFDataMgr.write(out, modelo, RDFFormat.RDFXML);
            }
 
        } catch (FileNotFoundException ex) {
            System.out.println("Fallo al escribir, fichero perdido");
        } catch (IOException ex) {
            System.out.println("Fallo al escribir, fichero desconectado");
        } 
        
        JOptionPane.showMessageDialog(this, "Se ha creado el fichero: " + filename, "GRAFO CREADO", JOptionPane.INFORMATION_MESSAGE);        
        initFilters();
    }//GEN-LAST:event_bSaveActionPerformed

    public void createGraph() {
        Theme theme;
        Untheme untheme;
        Language language;
        User user;
        Tweet tweet;
        String location;
        Tweet replyTweet;        
        String createdAt; 
        
        for (Status status : this.api.getStatus()) {
            theme = new Theme(this.URItheme + this.tThemeFind.getText(),
                    this.tfDescription.getText()); 
            
            untheme = new Untheme(this.URIuntheme + this.term, theme);
            
            language = new Language(this.URIlanguage + status.getLang(),                    
                    status.getLang(), getLanguage(status.getLang()));
            
            location = (status.getPlace() != null)? 
                    status.getPlace().getCountry() : status.getUser().getLocation();
            
            user = new User(this.URIuser + String.valueOf(status.getUser().getId()),
                    status.getUser().getScreenName(), location);
            
            theme.init(this.modelo);
            untheme.init(this.modelo);
            
            replyTweet = null;
            if (status.getInReplyToStatusId() > 0) {
                replyTweet = createReply(status, untheme);                               
            }
            
            createdAt = sdf.format(status.getCreatedAt()); 
            
            tweet = new Tweet(this.URItweet + String.valueOf(status.getId()), 
                    createdAt, String.valueOf(status.getId()),
                    status.getText(), user, language, untheme, replyTweet);            
            
            language.init(this.modelo);
            user.init(this.modelo);
            tweet.init(this.modelo);          
        }
    }
    
    private Tweet createReply(Status status, Untheme untheme) {
        String createdAt = sdf.format(status.getCreatedAt());
        
        String location = (status.getPlace() != null)? 
            status.getPlace().getCountry() : status.getUser().getLocation();
            
        User user = new User(this.URIuser + String.valueOf(status.getUser().getId()),
            status.getUser().getScreenName(), location);
        
        Language language = new Language(this.URIlanguage + status.getLang(),                    
                    status.getLang(), getLanguage(status.getLang()));
        
        Tweet tweet = new Tweet(this.URItweet + String.valueOf(status.getInReplyToStatusId()),
                createdAt, String.valueOf(status.getId()), 
                status.getText(), user, language, untheme, null);
        
        language.init(this.modelo);
        user.init(this.modelo);
        tweet.init(this.modelo);  
        
        return tweet;
    }
    
    private void printTweets() {
        String text = "";
        for (Status status : this.api.getStatus()) {
            text += "@" + status.getUser().getScreenName() + ": " + status.getText() + "\n\n";            
        }
        this.tfTweetsSearched.setText(text);
    }
    
    private String getLanguage(String code) {
        Locale loc = new Locale(code.toLowerCase(), code.toUpperCase());
        return loc.getDisplayLanguage(new Locale("es", "ES"));      
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PracticaJenaTwitter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PracticaJenaTwitter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PracticaJenaTwitter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PracticaJenaTwitter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PracticaJenaTwitter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConnect;
    private javax.swing.JButton bSave;
    private javax.swing.JButton bSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lUsername;
    private javax.swing.ButtonGroup outputFile;
    private javax.swing.JSpinner sMaxTweets;
    private javax.swing.JTextField tTermFind;
    private javax.swing.JTextField tThemeFind;
    private javax.swing.JTextArea tfDescription;
    private javax.swing.JTextArea tfTweetsSearched;
    private javax.swing.JRadioButton ttlFile;
    private javax.swing.JRadioButton xmlFile;
    // End of variables declaration//GEN-END:variables
}
